apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
spec:
  selector:
   matchLabels:
    app: apigateway
  replicas: 1
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: puppy-apigateway:latest
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - configMapRef:
                name: apigateway-config
---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: apigateway-config
      labels:
        app: apigateway
    data: 
      ASPNETCORE_ENVIRONMENT: Development
      ALLOWED_AUTH_ORIGINS: http://192.168.1.16:4100
---
    apiVersion: v1
    kind: Service
    metadata:
      name: apigateway
    spec:
       selector: 
        app: apigateway
       ports:
        - name: apigateway
          port: 80
          nodePort: 30902
       type: NodePort