apiVersion: apps/v1
kind: Deployment
metadata:
  name: computer-vision
spec:
  selector:
   matchLabels:
    app: computer-vision
  replicas: 1
  template:
    metadata:
      labels:
        app: computer-vision
    spec:
      containers:
        - name: computer-vision
          image: computer-vision:latest
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - configMapRef:
                name: computer-vision-config
---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: computer-vision-config
      labels:
        app: computer-vision
    data:
         SECRET: THIS_IS_A_RANDOM_SECRET_2e7a1e80-16ee-4e52-b5c6-5e8892453459
         ASPNETCORE_ENVIRONMENT: Development
         ALLOWED_AUTH_ORIGINS: http://192.168.1.16:4100
         FILE_SERVER: minio:9000
         FILE_SERVER_ACCESS_KEY: minio_access_key
         FILE_SERVER_SECRET_KEY: minio_secret_key
         APIGATEWAY_SERVER: minio:9000
         MESSAGEBROKER_USERNAME: puppy
         MESSAGEBROKER_PASSWORD: puppy
         MESSAGEBROKER_SERVER: rabbitmq://message-broker
---
    apiVersion: v1
    kind: Service
    metadata:
      name: computer-vision
    spec:
       selector: 
        app: computer-vision
       ports:
        - name: computer-vision
          port: 80
          nodePort: 30906
       type: NodePort